# Generated by Django 2.2.7 on 2019-11-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_status',
            field=models.IntegerField(default=1),
        ),
    ]
