# Generated by Django 2.2.7 on 2019-11-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_word_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='word_image',
            field=models.ImageField(default=1, upload_to='Word_Images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='word_to_learn',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='word_translation',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
