# Generated by Django 2.2.7 on 2019-11-10 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeinterval',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_intervals', to=settings.AUTH_USER_MODEL),
        ),
    ]
