# Generated by Django 2.2.7 on 2019-11-11 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('options', '0002_timeinterval_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status1', models.IntegerField(default=300)),
                ('status2', models.IntegerField(default=900)),
                ('status3', models.IntegerField(default=2700)),
                ('status4', models.IntegerField(default=7200)),
                ('status5', models.IntegerField(default=18000)),
                ('status6', models.IntegerField(default=86400)),
                ('status7', models.IntegerField(default=259200)),
                ('status8', models.IntegerField(default=2592000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_word_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepeatAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_per_day', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_repeats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
