# Generated by Django 2.2.7 on 2019-11-10 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0001_initial'),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='words.Word'),
        ),
    ]
