# Generated by Django 2.2.7 on 2019-11-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.IntegerField(verbose_name='Telegram User ID'),
        ),
    ]
