# Generated by Django 2.2.7 on 2019-11-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20191111_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reg_ok',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
