# Generated by Django 2.2.7 on 2019-11-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_user_reg_ok'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_ok',
            field=models.BooleanField(default=False),
        ),
    ]
