# Generated by Django 2.2.7 on 2019-11-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_auto_20191111_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reg_key',
            field=models.CharField(default=123, max_length=10, verbose_name='Registration key'),
        ),
    ]
